version: '3.0'
services:
  express_api_dev:
    container_name: express_api_dev
    build: .
    image: solenya_express_api
    user: node
    working_dir: /home/node/app
    labels:
      traefik.frontend.rule: "Host:TRAEFIK_ENV.chas.school"
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    ports:
      - 7770:7770
    env_file:
      - .env
  database:
    container_name: database
    image: onjin/alpine-postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  database:
